modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="overworld_ores"
version="1.0.0"
displayName="Overworld Ores"
displayURL="https://discord.gg/uqsY2667KK"
logoFile="logo.png"
credits="ShotUGMG"
authors="ShotUGMG"
description="Additional ores for the Overworld!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.overworld_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



