
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.overworldores.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.overworldores.OverworldOresMod;

public class OverworldOresModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, OverworldOresMod.MODID);
	public static final RegistryObject<CreativeModeTab> OVERWORLD_ORES = REGISTRY.register("overworld_ores",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.overworld_ores.overworld_ores")).icon(() -> new ItemStack(Items.IRON_PICKAXE)).displayItems((parameters, tabData) -> {
				tabData.accept(OverworldOresModItems.STONE_ROCK.get());
				tabData.accept(OverworldOresModItems.DEEPSLATE_ROCK.get());
				tabData.accept(OverworldOresModItems.ANDESITE_ROCK.get());
				tabData.accept(OverworldOresModItems.GRANITE_ROCK.get());
				tabData.accept(OverworldOresModItems.DIORITE_ROCK.get());
				tabData.accept(OverworldOresModItems.DRIPSTONE_ROCK.get());
				tabData.accept(OverworldOresModItems.BLACKSTONE_ROCK.get());
				tabData.accept(OverworldOresModItems.BASALT_ROCK.get());
				tabData.accept(OverworldOresModItems.NETHERRACK_ROCK.get());
				tabData.accept(OverworldOresModItems.CALCITE_ROCK.get());
				tabData.accept(OverworldOresModItems.MOSSY_STONE_ROCK.get());
				tabData.accept(OverworldOresModItems.TUFF_ROCK.get());
				tabData.accept(OverworldOresModItems.METEOR_STONE_ROCK.get());
				tabData.accept(OverworldOresModItems.RAW_ANCIENT_DEBRIS.get());
				tabData.accept(OverworldOresModItems.RAW_TIN.get());
				tabData.accept(OverworldOresModItems.TIN_INGOT.get());
				tabData.accept(OverworldOresModItems.TIN_SWORD.get());
				tabData.accept(OverworldOresModItems.TIN_PICKAXE.get());
				tabData.accept(OverworldOresModItems.TIN_AXE.get());
				tabData.accept(OverworldOresModItems.TIN_SHOVEL.get());
				tabData.accept(OverworldOresModItems.TIN_HOE.get());
				tabData.accept(OverworldOresModBlocks.TIN_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_RAW_TIN.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_TIN.get().asItem());
				tabData.accept(OverworldOresModItems.CRUSHED_COAL_ITEM.get());
				tabData.accept(OverworldOresModItems.IRON_COMPOSITE.get());
				tabData.accept(OverworldOresModItems.STEEL_INGOT.get());
				tabData.accept(OverworldOresModItems.STEEL_SWORD.get());
				tabData.accept(OverworldOresModItems.STEEL_PICKAXE.get());
				tabData.accept(OverworldOresModItems.STEEL_AXE.get());
				tabData.accept(OverworldOresModItems.STEEL_HOE.get());
				tabData.accept(OverworldOresModItems.STEEL_SHOVEL.get());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_STEEL.get().asItem());
				tabData.accept(OverworldOresModBlocks.CUT_STEEL.get().asItem());
				tabData.accept(OverworldOresModBlocks.STEEL_GRATE.get().asItem());
				tabData.accept(OverworldOresModItems.RAW_PLATINUM.get());
				tabData.accept(OverworldOresModItems.PLATINUM_INGOT.get());
				tabData.accept(OverworldOresModItems.PLATINUM_UPGRADE_TEMPLATE.get());
				tabData.accept(OverworldOresModItems.PLATINUM_SWORD.get());
				tabData.accept(OverworldOresModItems.PLATINUM_PICKAXE.get());
				tabData.accept(OverworldOresModItems.PLATINUM_AXE.get());
				tabData.accept(OverworldOresModItems.PLATINUM_SHOVEL.get());
				tabData.accept(OverworldOresModItems.PLATINUM_HOE.get());
				tabData.accept(OverworldOresModBlocks.PLATINUM_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_RAW_PLATINUM.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_PLATINUM.get().asItem());
				tabData.accept(OverworldOresModItems.TIN_ARMOR_HELMET.get());
				tabData.accept(OverworldOresModItems.TIN_ARMOR_CHESTPLATE.get());
				tabData.accept(OverworldOresModItems.TIN_ARMOR_LEGGINGS.get());
				tabData.accept(OverworldOresModItems.TIN_ARMOR_BOOTS.get());
				tabData.accept(OverworldOresModItems.PLATINUM_ARMOR_HELMET.get());
				tabData.accept(OverworldOresModItems.PLATINUM_ARMOR_CHESTPLATE.get());
				tabData.accept(OverworldOresModItems.PLATINUM_ARMOR_LEGGINGS.get());
				tabData.accept(OverworldOresModItems.PLATINUM_ARMOR_BOOTS.get());
				tabData.accept(OverworldOresModItems.STEEL_ARMOR_HELMET.get());
				tabData.accept(OverworldOresModItems.STEEL_ARMOR_CHESTPLATE.get());
				tabData.accept(OverworldOresModItems.STEEL_ARMOR_LEGGINGS.get());
				tabData.accept(OverworldOresModItems.STEEL_ARMOR_BOOTS.get());
				tabData.accept(OverworldOresModBlocks.ADAMANTITE_ORE.get().asItem());
				tabData.accept(OverworldOresModItems.RAW_ADAMANTITE.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_SCRAP.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_UPGRADE_TEMPLATE.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_INGOT.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_COMPOSITE.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_SWORD.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_PICKAXE.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_AXE.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_SHOVEL.get());
				tabData.accept(OverworldOresModItems.ADAMANTITE_HOE.get());
				tabData.accept(OverworldOresModItems.ADMANTITE_ARMOR_HELMET.get());
				tabData.accept(OverworldOresModItems.ADMANTITE_ARMOR_CHESTPLATE.get());
				tabData.accept(OverworldOresModItems.ADMANTITE_ARMOR_LEGGINGS.get());
				tabData.accept(OverworldOresModItems.ADMANTITE_ARMOR_BOOTS.get());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_RAW_ADAMANTITE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_ADAMANTITE.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_ORE.get().asItem());
				tabData.accept(OverworldOresModItems.RAW_SILVER.get());
				tabData.accept(OverworldOresModItems.SILVER_INGOT.get());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_RAW_SILVER.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_SILVER.get().asItem());
				tabData.accept(OverworldOresModBlocks.CHISLED_SILVER.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_GRATE.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_BRICKS.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_BRICK_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.S_ILVER_BRICK_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_TILES.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_TILE_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.SILVER_TILE_SLAB.get().asItem());
				tabData.accept(OverworldOresModItems.OBSIDIAN_SHARD.get());
				tabData.accept(OverworldOresModBlocks.METEOR_OLIVINE_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.OLIVINE_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_OLIVINE.get().asItem());
				tabData.accept(OverworldOresModItems.OLIVINE.get());
				tabData.accept(OverworldOresModItems.OLIVINE_NUGGET.get());
				tabData.accept(OverworldOresModBlocks.METOER_METAL.get().asItem());
				tabData.accept(OverworldOresModItems.METEORITE.get());
				tabData.accept(OverworldOresModItems.METEORITE_SCRAPS.get());
				tabData.accept(OverworldOresModItems.METEORITE_COMPOSITE.get());
				tabData.accept(OverworldOresModItems.METEORITE_ALLOY.get());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_METERITE_ALLOY.get().asItem());
				tabData.accept(OverworldOresModItems.OLIVINITE_ARMOR_HELMET.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_ARMOR_CHESTPLATE.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_ARMOR_LEGGINGS.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_ARMOR_BOOTS.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_SWORD.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_PICKAXE.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_SHOVEL.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_AXE.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_HOE.get());
				tabData.accept(OverworldOresModItems.OLIVINITE_SMITHING_TEMPLATE.get());
				tabData.accept(OverworldOresModBlocks.METEOR_ROCK.get().asItem());
				tabData.accept(OverworldOresModBlocks.POLISHED_METEOR_STONE.get().asItem());
				tabData.accept(OverworldOresModBlocks.POLISHED_METEOR_STONE_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.POLISHED_METEOR_STONE_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.CHISELED_METEOR_STONE.get().asItem());
				tabData.accept(OverworldOresModBlocks.CHISELED_METEOR_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_TILES.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_TILES_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_TILES_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_BRICKS.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_BRICK_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_BRICK_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.STACKED_METEOR_STONE_BRICKS.get().asItem());
				tabData.accept(OverworldOresModBlocks.STACKED_METEOR_STONE_BRICK_STAIRS.get().asItem());
				tabData.accept(OverworldOresModBlocks.STACKED_METEOR_STONE_BRICK_SLAB.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_WALL.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_PILLER.get().asItem());
				tabData.accept(OverworldOresModBlocks.METEOR_STONE_PANELS.get().asItem());
				tabData.accept(OverworldOresModItems.CHISEL.get());
				tabData.accept(OverworldOresModItems.SAPPHIRE.get());
				tabData.accept(OverworldOresModBlocks.SAPPHIRE_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.DEEPSLATE_SAPPHIRE_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_SAPPHIRE.get().asItem());
				tabData.accept(OverworldOresModItems.RUBY.get());
				tabData.accept(OverworldOresModBlocks.RUBY_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.DEEPSLATE_RUBY_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_RUBY.get().asItem());
				tabData.accept(OverworldOresModItems.ALEXANDRITE.get());
				tabData.accept(OverworldOresModBlocks.ALEXANDRITE_ORE.get().asItem());
				tabData.accept(OverworldOresModBlocks.BLOCK_OF_ALEXANDRITE.get().asItem());
			}).withSearchBar().build());
}
